---
- name: Install prerequisites
  apt:
    name:
      - python3-dev
      - python3-pip
      - pkg-config
      - libsystemd-dev

- name: Clone prometheus_smart_exporter repo to temporary directory
  git:
    repo: https://github.com/RaptahJezus/prometheus_smart_exporter.git
    dest: /tmp/prometheus_smart_exporter


- name: Install prometheus_smart_exporter via pip3
  ansible.builtin.pip:
    name: .
    chdir: /tmp/prometheus_smart_exporter
  notify: restart prometheus_smart_helper

- name: Create prometheus smart exporter user
  user:
    name: prometheus
    shell: /sbin/nologin
    state: present

- name: Create /etc/prometheus_smart_exporter
  file:
    path: /etc/prometheus_smart_exporter
    state: directory
    owner: root
    group: root

- name: Copy device DB json file
  template:
    src: devices.json.j2
    dest: /etc/prometheus_smart_exporter/devices.json
    owner: root
    group: root
  notify: restart prometheus_smart_helper

- name: Copy the smart_exporter systemd file
  template:
    src: prometheus_smart_exporter.service.j2
    dest: /etc/systemd/system/prometheus_smart_exporter.service
    mode: 0644
  register: prometheus_smart_exporter_service
  notify: restart prometheus_smart_helper

- name: Copy the smart_helper systemd file
  template:
    src: prometheus_smart_helper.service.j2
    dest: /etc/systemd/system/prometheus_smart_helper.service
    mode: 0644
  register: prometheus_smart_exporter_service
  notify: restart prometheus_smart_helper

- name: Copy the smart_helper socket file
  template:
    src: prometheus_smart_helper.socket.j2
    dest: /etc/systemd/system/prometheus_smart_helper.socket
    mode: 0644
  register: prometheus_smart_exporter_service
  notify: restart prometheus_smart_helper



- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart prometheus_smart_helper
#  when: prometheus_smart_exporter_service is changed