---
- name: add grafana repo key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    filename: grafana
    update_cache: yes
    state: present

- name: install grafana
  ansible.builtin.apt:
    name:
      - grafana
    update_cache: yes
    state: present
