---
- name: add grafana repo key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    filename: grafana
    update_cache: yes
    state: present

- name: install grafana
  ansible.builtin.apt:
    name:
      - grafana
    update_cache: yes
    state: present

- name: create grafana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: dan
    group: dan
    mode: 0775
  loop:
    - /lxc-data/grafana
    - /lxc-data/grafana/data
    - /lxc-data/grafana/log
    - /lxc-data/grafana/provisioning

- name: copy grafana default config
  template:
    src: default-grafana-server
    dest: /etc/default/grafana-server
    owner: root
    group: root
    mode: '755'
  notify:
    - restart grafana

- name: copy grafana systemd file
  template:
    src: grafana-server-systemd
    dest: /etc/systemd/system/grafana-server.service
    owner: root
    group: root
    mode: '755'
  notify:
    - restart grafana