---
- hosts: 'homeassistant-2'
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - passwd.yml
  roles:
#   - role: common
#   - role: postfix-gmail-relay
#   - role: ssh-secure
#   - role: dotfiles
#   - role: unattended-upgrades
   - role: homeassistant

  vars:
    email: "{{ vault_dan_email }}"
    auto_reboot: false 
    auto_reboot_time: '04:30'


