---
- hosts: nginx
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - passwd.yml
    - rev_proxy_sites.yml
  roles:
    - role: common
    - role: postfix-gmail-relay
    - role: ssh-secure
    - role: dotfiles
    - role: unattended-upgrades
    - role: nginx-revproxy
  
  vars:
    email: "{{ vault_dan_email }}"
    auto_reboot: false 
    auto_reboot_time: '04:30'

