---

- name: Update python venv permissions
  ansible.builtin.file:
    path: /srv/homeassistant
    state: directory
    recurse: yes
    owner: dan
    group: dan

- name: Restart homeassistant
  ansible.builtin.systemd:
    name: hass
    state: restarted

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable homeassistant
  ansible.builtin.systemd:
    name: hass
    enabled: yes