---

- name: install required packages
  apt:
    name:
      - needrestart
      - unattended-upgrades
  become: true

- name: copy needrestart config
  template:
    src: needrestart.conf.j2
    dest: /etc/needrestart/needrestart.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: copy 50unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: true