---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - dirmngr 
      - gnupg
      - ca-certificates
      - mediainfo
      - sqlite3
    state: present    

- name: check radarr releases
  uri:
    url: https://api.github.com/repos/Radarr/Radarr/releases/latest
    return_content: true
  register: json_response

- name: set download URL
  set_fact:
    download_url: "{{ json_response.json.assets | json_query(jq) }}"
  vars:
    jq: "[?contains(name, 'linux-core-x64')].browser_download_url | [0]"

- name: install latest radarr 
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ download_url }}"
    dest: "/opt"
    keep_newer: yes
    group: dan
    owner: dan

- name: Change radarr data directory permissions
  file:
    path: /lxc-data
    state: directory
    recurse: yes
    owner: dan
    group: dan
    mode: '755'

- name: copy systemd file
  template:
    src: radarr.service.j2
    dest: /etc/systemd/system/radarr.service
    owner: root
    group: root
    mode: '755'
  notify: 
    - restart radarr