- name: check for xmlrpc-c installed
  command: dpkg-query -W xmlrpc-c
  register: check_xmlrpc_c_deb
  failed_when: check_xmlrpc_c_deb.rc > 1
  changed_when: check_xmlrpc_c_deb.rc == 1

- name: copy xmlrpc-c
  copy:
    src: xmlrpc-c_1.39.12-1_amd64.deb
    dest: /tmp/xmlrpc-c_1.39.12-1_amd64.deb
  when: check_xmlrpc_c_deb.rc == 1

- name: install xmlrpc-c
  ansible.builtin.apt:
    deb: /tmp/xmlrpc-c_1.39.12-1_amd64.deb
  when: check_xmlrpc_c_deb.rc == 1

- name: check for libtorrent installed
  command: dpkg-query -W libtorrent
  register: check_libtorrent_deb
  failed_when: check_libtorrent_deb.rc > 1
  changed_when: check_libtorrent_deb.rc == 1

- name: copy libtorrent
  copy:
    src: libtorrent_0.13.8-1_amd64.deb
    dest: /tmp/libtorrent_0.13.8-1_amd64.deb
  when: check_libtorrent_deb.rc == 1

- name: install libtorrent
  ansible.builtin.apt:
    deb: /tmp/libtorrent_0.13.8-1_amd64.deb
  when: check_libtorrent_deb.rc == 1

- name: check for rtorrent installed
  command: dpkg-query -W rtorrent
  register: check_rtorrent_deb
  failed_when: check_rtorrent_deb.rc > 1
  changed_when: check_rtorrent_deb.rc == 1

- name: copy rtorrent
  copy:
    src: rtorrent_0.9.8-1_amd64.deb
    dest: /tmp/rtorrent_0.9.8-1_amd64.deb
  when: check_rtorrent_deb.rc == 1

- name: install rtorrent
  ansible.builtin.apt:
    deb: /tmp/rtorrent_0.9.8-1_amd64.deb
  when: check_rtorrent_deb.rc == 1

- name: transfer rtorrent.rc
  ansible.builtin.template:
    src: rtorrent.rc.j2
    dest: /home/dan/.rtorrent.rc
    owner: dan
    group: dan
  notify: restart rtorrent

- name: transfer rtorrent systemd file
  ansible.builtin.template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service
    owner: root
    group: root
  notify: restart rtorrent