---
- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false

- name: create prometheus DB data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  when:
    - not prometheus_skip_install

- block:
  - name: download prometheus binary to local folder
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
      dest: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch}}.tar.gz"
    delegate_to: localhost
    when:
      - not prometheus_skip_install

  - name: unpack prometheus binaries
    unarchive:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
      dest: "/tmp"
      creates: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/prometheus"
    delegate_to: localhost
    when:
      - not prometheus_skip_install
  - name: propagate official prometheus and promtool binaries
    copy:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: 0755
      owner: root
      group: root
    with_items:
      - prometheus
      - promtool
    notify:
        - restart prometheus
    when:
      - not prometheus_skip_install

  - name: add prometheus systemd file
    template:
      src: prometheus.service.j2
      dest: /etc/systemd/system/prometheus.service
      owner: root
      group: root
      mode: 0644
    notify:
      - restart prometheus
    when:
      - not prometheus_skip_install

  - name: copy prometheus.yml config file
    template:
      src: prometheus.yml.j2
      dest: /lxc-data/prometheus/prometheus.yml
      force: true
      owner: root
      group: prometheus
      mode: 0640
    notify:
      - reload prometheus
