---

- name: Apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 240

- name: Set timezone
  become: true
  file:
    src: /usr/share/zoneinfo/America/New_York
    dest: /etc/localtime
    state: link

- name: Set locale
  become: true
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: LANG=C.UTF-8

- name: Install packages
  become: true
  apt:
    name:
      - tar
      - sudo
      - git
      - gcc
      - make
      - software-properties-common
      - tmux
      - unzip
    state: present


