---
- name: Install Packages
  apt:
    name:
      - python3 
      - python3-dev 
      - python3-venv 
      - python3-pip 
      - python3-virtualenv
      - libffi-dev 
      - libssl-dev 
      - libjpeg-dev 
      - zlib1g-dev 
      - autoconf 
      - build-essential 
      - libopenjp2-7 
      - libtiff5 
      - libturbojpeg0 
      - tzdata
    state: present

- name: Create Python Venv Directory
  ansible.builtin.file:
    path: /srv/homeassistant
    state: directory
    owner: dan
    group: dan
  notify:
    - Update python venv permissions
    - Restart homeassistant

- name: Pip install Wheel
  pip:
    name: wheel
    virtualenv: /srv/homeassistant
    virtualenv_python: python3.9
  notify:
    - Update python venv permissions
    - Restart homeassistant

- name: Pip install HomeAssistant
  pip:
    name: homeassistant
    virtualenv: /srv/homeassistant
    virtualenv_python: python3.9
  notify:
    - Update python venv permissions
    - Restart homeassistant

- name: Pip install pymysql
  pip:
    name: pymysql
    virtualenv: /srv/homeassistant
    virtualenv_python: python3.9
  notify:
    - Update python venv permissions
    - Restart homeassistant

- name: Create HomeAssistant config directory
  ansible.builtin.file:
    path: /lxc-data/homeassistant
    state: directory
    owner: dan
    group: dan
  notify:
    - Restart homeassistant

- name: Copy Systemd File
  template:
    src: hass-systemd.j2
    dest: /etc/systemd/system/hass.service
  notify:
    - Daemon reload
    - Enable homeassistant
    - Restart homeassistant



