---

- name: "install node-red"
  community.general.npm:
    name: node-red
    state: present
    global: yes
    unsafe_perm: yes
  notify:
    - Daemon reload
    - Restart node-red

- name: "Create node-red data directory"
  ansible.builtin.file:
    path: "/lxc-data/node-red"
    state: directory
    owner: dan
    group: dan
    mode: "0755"
  notify:
    - Daemon reload
    - Restart node-red

- name: "Install node-red packages"
  community.general.npm:
    name: "{{ item }}"
    path: /lxc-data/node-red
  loop:
    - node-red-contrib-bigtimer
    - node-red-contrib-home-assistant-websocket
    - node-red-dashboard
    - node-red-node-base64
    - node-red-contrib-traffic
    - node-red-contrib-broadlink
    - node-red-contrib-cast
    - node-red-contrib-counter
    - node-red-contrib-merge-topic
    - node-red-contrib-looptimer
    - node-red-contrib-stoptimer
    - node-red-contrib-weekday
    - node-red-contrib-time-range-switch
    - node-red-contrib-telegrambot
    - node-red-node-random
    - node-red-contrib-google
    - node-red-contrib-zigbee2mqtt
    - node-red-node-tail
    - node-red-node-pushbullet
    - node-red-node-email
    - node-red-contrib-moment
  notify:
    - Restart node-red

- name: "Copy node-red service file"
  ansible.builtin.template:
    src: node-red.service.j2
    dest: "/etc/systemd/system/node-red.service"
  notify:
    - Daemon reload
    - Restart node-red





